version: "3"

services:
  namenode:
    image: dubachphil/hadoop_namenode
    ports:
      - 9870:9870
      - 8020:8020
    environment:
      - CLUSTER_NAME=hadoop_cluster
    env_file:
      - ./hadoop.env

  datanode:
    image: dubachphil/hadoop_datanode
    ports:
      - 9864-9900:9864
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env

  resourcemanager:
    image: dubachphil/hadoop_resourcemanager
    ports:
      - 8088:8088
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864"
    depends_on:
      - namenode
      - datanode
    env_file:
      - ./hadoop.env

  nodemanager:
    image: dubachphil/hadoop_nodemanager
    ports:
      - 8042-8050:8042
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    depends_on:
      - resourcemanager
    env_file:
      - ./hadoop.env
  
  historyserver:
    image: dubachphil/hadoop_historyserver
    ports:
      - 8188:8188
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 resourcemanager:8088"
    depends_on:
      - nodemanager
    env_file:
      - ./hadoop.env

  spark-master:
    image: dubachphil/spark_master
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    depends_on:
      - historyserver
    environment:
      - INIT_DAEMON_STEP=setup_spark
    env_file:
      - ./hadoop.env

  spark-worker:
    image: dubachphil/spark_worker
    ports:
      - 8081-8087:8081
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      - ./hadoop.env

  zeppelin:
    image: dubachphil/zeppelin
    ports:
      - 80:9999
    environment:
      - "CORE_CONF_fs_defaultFS=hdfs://namenode:8020"
      - "SPARK_MASTER=spark://spark-master:7077"
      - "MASTER=spark://spark-master:7077"
      - "ZEPPELIN_PORT=9999"
    volumes:
      - zeppelin_notes:/opt/zeppelin/notebook
    depends_on:
      - spark-master
      - namenode
    env_file:
      - ./hadoop.env

volumes:
  zeppelin_notes:
